#!/usr/bin/env python3
"""Export the `decisions` SQLite table to a human-readable Markdown file.

The decisions table is the structured source of truth. This exporter
produces the human surface (`logs/decisions/decisions.md`) so Chen can
scan past actions, rationales, and outcomes without running SQL.

Format per entry: a short header with id/ts/agent/outcome + a 4-line
body with summary, trigger, rationale, and (if present) expected
impact. Designed to fit ~25 entries per screen for skimmability.

Re-running rewrites the file from scratch (the table is the source of
truth). Idempotent.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path
from textwrap import indent
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def fetch_all(conn: sqlite3.Connection) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            d.id, d.ts, d.agent, d.decision_type, d.summary, d.rationale,
            d.trigger_metric, d.trigger_value, d.expected_impact,
            d.experiment_id, d.outcome, d.outcome_metric, d.notes,
            e.proposal AS experiment_proposal,
            e.stage AS experiment_stage,
            e.branch AS experiment_branch
        FROM decisions d
        LEFT JOIN experiments e ON e.id = d.experiment_id
        ORDER BY d.ts DESC, d.id DESC
        """
    ).fetchall()
    cols = [
        "id", "ts", "agent", "decision_type", "summary", "rationale",
        "trigger_metric", "trigger_value", "expected_impact",
        "experiment_id", "outcome", "outcome_metric", "notes",
        "experiment_proposal", "experiment_stage", "experiment_branch",
    ]
    return [dict(zip(cols, row, strict=False)) for row in rows]


_OUTCOME_GLYPHS = {
    "pending":     "⏳",
    "approved":    "✅",
    "rejected":    "❌",
    "rolled_back": "🔙",
    "kept":        "✅",
}


def render(entries: list[dict[str, Any]]) -> str:
    if not entries:
        return (
            "# Decisions Log\n\n"
            "*No decisions recorded yet. The self-improvement loop has not "
            "produced any behavioral changes — this is expected during M1, "
            "which is pure instrumentation.*\n"
        )

    lines: list[str] = ["# Decisions Log\n"]
    lines.append(
        "Source of truth: `decisions` table in `data/trading.db`. "
        "Regenerated by `scripts/self_improve/export_decisions.py`. "
        "Each entry: what changed, why, what triggered it, and the outcome."
    )
    lines.append("")
    lines.append(f"**Total entries:** {len(entries)}")
    lines.append("")

    for e in entries:
        glyph = _OUTCOME_GLYPHS.get(e["outcome"] or "", "•")
        header = (
            f"## #{e['id']} — {glyph} {e['summary'] or '(no summary)'}"
        )
        meta_bits = [
            f"**ts:** `{e['ts']}`",
            f"**agent:** `{e['agent']}`",
            f"**type:** `{e['decision_type']}`",
            f"**outcome:** `{e['outcome'] or 'unset'}`",
        ]
        if e["experiment_id"]:
            meta_bits.append(
                f"**experiment:** #{e['experiment_id']} "
                f"({e['experiment_stage'] or '?'})"
            )
        if e["experiment_branch"]:
            meta_bits.append(f"**branch:** `{e['experiment_branch']}`")

        lines.append(header)
        lines.append(" | ".join(meta_bits))
        lines.append("")

        if e["trigger_metric"]:
            trig = (
                f"`{e['trigger_metric']}` = {e['trigger_value']}"
                if e["trigger_value"] is not None
                else f"`{e['trigger_metric']}`"
            )
            lines.append(f"**Trigger:** {trig}")
        if e["rationale"]:
            lines.append("**Rationale:**")
            lines.append("")
            lines.append(indent(e["rationale"].rstrip(), "> "))
        if e["expected_impact"]:
            lines.append(f"**Expected impact:** {e['expected_impact']}")
        if e["outcome_metric"] is not None:
            lines.append(f"**Outcome metric:** {e['outcome_metric']}")
        if e["notes"]:
            lines.append(f"**Notes:** {e['notes']}")

        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def export(db_path: Path, out_path: Path) -> dict[str, int]:
    with sqlite3.connect(str(db_path)) as conn:
        entries = fetch_all(conn)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(entries), encoding="utf-8")
    return {"entries": len(entries)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--db", default="data/trading.db")
    parser.add_argument("--out", default="logs/decisions/decisions.md")
    args = parser.parse_args(argv)

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"❌ DB not found at {db_path}", file=sys.stderr)
        return 2

    stats = export(db_path, Path(args.out))
    print(f"✅ Exported {stats['entries']} decisions → {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
